In [ ]:
import cv2
import numpy as np

img = cv2.imread('..\\dos\\dataset3\\shape3.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, img2 = cv2.threshold(gray, 125, 255, cv2.THRESH_BINARY)
c, h = cv2.findContours(img2, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

hull1 = cv2.convexHull(c[0])
hull2 = cv2.convexHull(c[0], returnPoints=False)
print('returnPoints=True时返回的凸包：\n', hull1)
print('returnPoints=False时返回的凸包：\n', hull2)

img3 = np.zeros(img.shape, np.uint8) + 255
cv2.drawContours(img3, c, -1, (0, 0, 255), 2)
cv2.polylines(img3, [hull1], True, (255, 0, 0), 2)
cv2.imshow('Convex Hull', img3)
cv2.waitKey(0)

returnPoints=True时返回的凸包：
 [[[228  72]]

 [[227 131]]

 [[165 162]]

 [[102 131]]

 [[101  72]]

 [[165  42]]]
returnPoints=False时返回的凸包：
 [[124]
 [ 86]
 [ 68]
 [ 52]
 [ 14]
 [  0]]
